apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
data:
{{- range $k, $v:= .Values.configs }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
  environment: {{ .Values.global.environment }}
  init.sql: |
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
    USE app_db;
    CREATE TABLE counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );
