apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.common.namespace }}
data:
  ENVIRONMENT: {{ .Values.global.environment | quote }}
{{- range $k, $v := .Values.kube2py.configs  }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
  {{- if eq .Values.global.environment "Production" }}
  ENV_DETAILS: "Safe To Test"
  {{- end }}