
common:
  environment: "Staging"

mysql:
  namespace: mysql-staging

kube2py:
  configs:
    APP_ENV: "User-Testing"
  secrets:
    password: MyStrongerPassword

  resources:
    requests:
       memory: "256Mi"
       cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 5